version: "3.8"

services:
  frontend:
    build:
      context: frontend
      args:
        VITE_API_ORIGIN: ${VITE_API_ORIGIN:-http://localhost:3000/api}
        VITE_CDN_ORIGIN: ${VITE_CDN_ORIGIN:-http://localhost:3000}
    environment:
      - VITE_API_ORIGIN=${VITE_API_ORIGIN:-http://localhost:3000/api}
      - VITE_CDN_ORIGIN=${VITE_CDN_ORIGIN:-http://localhost:3000}
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    command: npm run dev -- --host 0.0.0.0
    networks:
      - internal

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-example}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-weblarek}
    volumes:
      - db:/data/db
      - ./.dump:/dump
    ports:
      - "${MONGO_PORT:-27017}:27017"
    networks:
      - internal

  backend:
    restart: always
    build:
      context: backend
      args:
        NODE_ENV: ${NODE_ENV:-development}
    env_file:
      - backend/.env
    environment:
      - PORT=${BACKEND_PORT:-3000}
      - NODE_ENV=${NODE_ENV:-development}
      - DB_ADDRESS=${DB_ADDRESS:-mongodb://root:example@mongo:27017/weblarek?authSource=admin}
      - AUTH_ACCESS_TOKEN_SECRET=${AUTH_ACCESS_TOKEN_SECRET}
      - AUTH_REFRESH_TOKEN_SECRET=${AUTH_REFRESH_TOKEN_SECRET}
      - AUTH_ACCESS_TOKEN_EXPIRY=${AUTH_ACCESS_TOKEN_EXPIRY:-10m}
      - AUTH_REFRESH_TOKEN_EXPIRY=${AUTH_REFRESH_TOKEN_EXPIRY:-7d}
      - CSRF_SECRET=${CSRF_SECRET}
      - UPLOAD_PATH=${UPLOAD_PATH:-images}
      - UPLOAD_PATH_TEMP=${UPLOAD_PATH_TEMP:-temp}
      - ORIGIN_ALLOW=${ORIGIN_ALLOW:-http://localhost:5173,http://127.0.0.1:5173,http://localhost}
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/images:/app/images
      - ./backend/temp:/app/temp
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    command: npm run dev
    networks:
      - internal
    depends_on:
      - mongo

  nginx:
    build:
      context: nginx
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./backend/images:/var/public/images
      - ./frontend/dist:/var/app
    depends_on:
      - frontend
      - backend
    networks:
      - internal

volumes:
  db:

networks:
  internal:
    driver: bridge
