version: "3.8"

services:
  frontend:
    build:
      context: frontend
      args:
        VITE_API_ORIGIN: ${VITE_API_ORIGIN}
        VITE_CDN_ORIGIN: ${VITE_CDN_ORIGIN}
    environment:
      - VITE_API_ORIGIN=${VITE_API_ORIGIN}
      - VITE_CDN_ORIGIN=${VITE_CDN_ORIGIN}
    networks:
      - internal

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - db:/data/db
      - ./.dump:/dump
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      - internal

  backend:
    restart: always
    build:
      context: backend
      args:
        NODE_ENV: ${NODE_ENV}
    env_file:
      - backend/.env
    environment:
      - PORT=${BACKEND_PORT}
      - NODE_ENV=${NODE_ENV}
      - DB_ADDRESS=${DB_ADDRESS}
      - JWT_SECRET=${JWT_SECRET}
      - AUTH_ACCESS_TOKEN_SECRET=${AUTH_ACCESS_TOKEN_SECRET}
      - AUTH_REFRESH_TOKEN_SECRET=${AUTH_REFRESH_TOKEN_SECRET}
      - AUTH_ACCESS_TOKEN_EXPIRY=${AUTH_ACCESS_TOKEN_EXPIRY}
      - AUTH_REFRESH_TOKEN_EXPIRY=${AUTH_REFRESH_TOKEN_EXPIRY}
      - CSRF_SECRET=${CSRF_SECRET}
      - UPLOAD_PATH=${UPLOAD_PATH}
      - UPLOAD_PATH_TEMP=${UPLOAD_PATH_TEMP}
      - ORIGIN_ALLOW=${ORIGIN_ALLOW}
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/images:/app/images
      - ./backend/temp:/app/temp
    ports:
      - "${BACKEND_PORT}:3000"
    command: npm run dev
    networks:
      - internal
    depends_on:
      - mongo

  nginx:
    build:
      context: nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./backend/images:/var/public/images
      - ./frontend/dist:/var/app
    depends_on:
      - frontend
      - backend
    networks:
      - internal

volumes:
  db:

networks:
  internal:
    driver: bridge
